enum EVENT{
	EVENT_LOGIN_OK = SDL_USEREVENT,
	EVENT_LOGIN_DENY,
	EVENT_LOGIN_SESSION_EXIST,

	EVENT_LOGOUT_OK,
	EVENT_LOGOUT_ERR,

	EVENT_SIGNUP_OK,
	EVENT_SIGNUP_ERR_ID,
	EVENT_SIGNUP_ERR_UNKNOWN,

	EVENT_TANK_JOIN,
	EVENT_TANK_MOVE,
	EVENT_TANK_LEAVE
	};